// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABz3jSVWS4mOazqDSAwm4kF2ezhgmed68',
    appId: '1:396840387567:web:c35c5052b6c4a97929ec1a',
    messagingSenderId: '396840387567',
    projectId: 'fir-backend-613bb',
    authDomain: 'fir-backend-613bb.firebaseapp.com',
    storageBucket: 'fir-backend-613bb.appspot.com',
    measurementId: 'G-8NWT4VLHRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjYcpdBrfC4xdPP9gg2FoVEwlDf-dMVs8',
    appId: '1:396840387567:android:375172c166c1e44a29ec1a',
    messagingSenderId: '396840387567',
    projectId: 'fir-backend-613bb',
    storageBucket: 'fir-backend-613bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4D2LgETIGE45EGCbaUk4urdtQmKbHytY',
    appId: '1:396840387567:ios:71c22ad9761c420629ec1a',
    messagingSenderId: '396840387567',
    projectId: 'fir-backend-613bb',
    storageBucket: 'fir-backend-613bb.appspot.com',
    iosBundleId: 'com.example.brakedownAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4D2LgETIGE45EGCbaUk4urdtQmKbHytY',
    appId: '1:396840387567:ios:71c22ad9761c420629ec1a',
    messagingSenderId: '396840387567',
    projectId: 'fir-backend-613bb',
    storageBucket: 'fir-backend-613bb.appspot.com',
    iosBundleId: 'com.example.brakedownAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABz3jSVWS4mOazqDSAwm4kF2ezhgmed68',
    appId: '1:396840387567:web:0fb854ecabe66be629ec1a',
    messagingSenderId: '396840387567',
    projectId: 'fir-backend-613bb',
    authDomain: 'fir-backend-613bb.firebaseapp.com',
    storageBucket: 'fir-backend-613bb.appspot.com',
    measurementId: 'G-87T438XG9M',
  );
}
